### ISSUE TITLE
Change email address associated with account

### ISSUE THREAD

**Issue by chelciesansmerci** [clirdlf/participatory_voting#13]
Is it possible to change the email address associated with the participatory voting web app for those of us who have changed institutions? Thanks!

**Comment by waynegraham** [comment]
This app doesn't currently have very robust user management features as it's really just meant to keep bots at bay (as much as one can). All the votes get deleted when re update the proposals each year, so the easiest thing to do is just create a new account.

**Comment by chelciesansmerci** [comment]
Okay! Many thanks.
